name: Build project

on: 
   workflow_dispatch: 
    inputs:
      tag:
        description: 'New tag name'
        required: true
      name:
        description: 'Release name'
        required: true

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  
  
  buildAndroid:
    name: Build for Android 📱
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-Android
          restore-keys: |
            Library-build-
            Library-
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
      - name: upload Android artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/Android
          asset_name: build-Android.zip
          asset_content_type: application/zip
      



